### ISSUE TITLE
Reading Itho heat pump with other hardware

### ISSUE THREAD

**Issue by PeterLourens** [pommi/python-itho-wpu#5]
Hi Pim,

Thanks for the great software, it is a good reference for my project. I try to do the same but then with different hardware. I wonder if you can have a look at my questions. I posted it on [this forum](https://gathering.tweakers.net/forum/list_messages/2092400)

Thanks in advance 

Peter L

**Comment by pommi** [comment]
Hi Peter, Thanks for your question. I've read the forum post on Tweakers, but unfortunately I also don't understand why you get the response you get from the ITHO device. I also don't have Arduino hardware to reproduced the issue.
